// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package api2

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// __getArtifactsByTypeInput is used internally by genqlient
type __getArtifactsByTypeInput struct {
	OrganizationId string `json:"organizationId"`
	ArtifactType   string `json:"artifactType"`
}

// GetOrganizationId returns __getArtifactsByTypeInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__getArtifactsByTypeInput) GetOrganizationId() string { return v.OrganizationId }

// GetArtifactType returns __getArtifactsByTypeInput.ArtifactType, and is useful for accessing the field via an interface.
func (v *__getArtifactsByTypeInput) GetArtifactType() string { return v.ArtifactType }

// getArtifactsByTypeArtifactsPaginatedArtifacts includes the requested fields of the GraphQL type PaginatedArtifacts.
type getArtifactsByTypeArtifactsPaginatedArtifacts struct {
	// A cursor to the next page of items in the list.
	Next string `json:"next"`
	// A list of type artifact.
	Items []getArtifactsByTypeArtifactsPaginatedArtifactsItemsArtifact `json:"items"`
}

// GetNext returns getArtifactsByTypeArtifactsPaginatedArtifacts.Next, and is useful for accessing the field via an interface.
func (v *getArtifactsByTypeArtifactsPaginatedArtifacts) GetNext() string { return v.Next }

// GetItems returns getArtifactsByTypeArtifactsPaginatedArtifacts.Items, and is useful for accessing the field via an interface.
func (v *getArtifactsByTypeArtifactsPaginatedArtifacts) GetItems() []getArtifactsByTypeArtifactsPaginatedArtifactsItemsArtifact {
	return v.Items
}

// getArtifactsByTypeArtifactsPaginatedArtifactsItemsArtifact includes the requested fields of the GraphQL type Artifact.
type getArtifactsByTypeArtifactsPaginatedArtifactsItemsArtifact struct {
	Name string `json:"name"`
	Id   string `json:"id"`
}

// GetName returns getArtifactsByTypeArtifactsPaginatedArtifactsItemsArtifact.Name, and is useful for accessing the field via an interface.
func (v *getArtifactsByTypeArtifactsPaginatedArtifactsItemsArtifact) GetName() string { return v.Name }

// GetId returns getArtifactsByTypeArtifactsPaginatedArtifactsItemsArtifact.Id, and is useful for accessing the field via an interface.
func (v *getArtifactsByTypeArtifactsPaginatedArtifactsItemsArtifact) GetId() string { return v.Id }

// getArtifactsByTypeResponse is returned by getArtifactsByType on success.
type getArtifactsByTypeResponse struct {
	// List all artifacts
	Artifacts getArtifactsByTypeArtifactsPaginatedArtifacts `json:"artifacts"`
}

// GetArtifacts returns getArtifactsByTypeResponse.Artifacts, and is useful for accessing the field via an interface.
func (v *getArtifactsByTypeResponse) GetArtifacts() getArtifactsByTypeArtifactsPaginatedArtifacts {
	return v.Artifacts
}

func getArtifactsByType(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	artifactType string,
) (*getArtifactsByTypeResponse, error) {
	req := &graphql.Request{
		OpName: "getArtifactsByType",
		Query: `
query getArtifactsByType ($organizationId: ID!, $artifactType: String!) {
	artifacts(organizationId: $organizationId, input: {filter:{type:$artifactType}}) {
		next
		items {
			name
			id
		}
	}
}
`,
		Variables: &__getArtifactsByTypeInput{
			OrganizationId: organizationId,
			ArtifactType:   artifactType,
		},
	}
	var err error

	var data getArtifactsByTypeResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
